Jelly: Add `User-Agent` property to suggestions request headers
* Some search suggestions providers (e.g. Brave) check this
  property before serving any suggestions, possibly as a means
  to force developers to use their paid APIs.

* A simple fix is to add this property without actually
  providing the real value, which appears to work with Brave.

Error logs for reference:
java.io.FileNotFoundException: https://search.brave.com/api/suggest?q=a
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
    at java.net.URL.openStream(URL.java:1072)
    at kotlin.io.TextStreamsKt.readBytes(ReadWrite.kt:155)
    ...

(cherry picked from commit 3d368593a558abc6dd1ece30cd82e1cd8bf7ccaf)
(cherry picked from https://codeberg.org/TipzTeam/viola/commit/3d368593a558abc6dd1ece30cd82e1cd8bf7ccaf)
Change-Id: I54864e1ba5978a6b38635f7b62f5a8da2992cdbd
Signed-off-by: Ricky Cheung <rcheung844@gmail.com>